### ISSUE TITLE
Failed to load https://api.imgur.com/3/image:

### ISSUE THREAD

**Issue by leo5j472421** [carry0987/CKEditor-Imgur#1]
再設定完 config.imgurClientId 之後 上傳失敗 請問有需要設定?

ImgurClientSecret 嗎?

這裡是 config 設定檔 和 錯誤訊息 請問是那裡出錯了? 謝謝

![image](https://user-images.githubusercontent.com/8470722/38231026-521fbdb2-3743-11e8-9be5-1c1ebb171451.png)

![image](https://user-images.githubusercontent.com/8470722/38230980-2a1a8504-3743-11e8-9917-d563e84e2cc6.png)

**Comment by leo5j472421** [comment]
好像是 會跟 meta 的 csrf 衝突到 請問有甚麼方法可以在 不拿掉 meta 的 csrf token 下順利執行?

**Comment by carry0987** [comment]
@leo5j472421  May I see your test site?
